production:
  default: &default
    delivery_method: test
    smtp_settings:
      address: 'smtp.gmail.com'
      port: 587

  invalid_provider:
    <<: *default
    provider: "google"
  sendgrid:
    <<: *default
    provider: sendgrid
    smtp_settings:
      address: "smtp.sendgrid.net"
      port: '587'
      enable_starttls_auto: true
      domain: "example.com"
      authentication: 'plain'
      user_name: "test@example.com"
      password: "superamazingpasswordforsendgrid"
  mailgun:
    <<: *default
    provider: mailgun
    smtp_settings:
      address: "smtp.mailgun.org"
      port: '587'
      enable_starttls_auto: true
      user_name: "test@example.com"
      password: "superamazingpasswordformailgun"


